services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  migrate:
    image: migrate/migrate:latest
    env_file:
      - .env
    volumes:
      - ../internal/ordering/infra/postgres/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      - postgres
    networks:
      - mynetwork
  firstbeego:
    image: firstbeego:1.0
    ports: 
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - app.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
