services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  migrate:
    image: migrate/migrate:latest
    env_file:
      - .env
    volumes:
      - ../internal/ordering/infra/postgres/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      - postgres
    networks:
      - mynetwork
  firstbeegoapi:
    container_name: firstbeegoapi
    build:
      context: ..
      dockerfile: Dockerfile
    image: firstbeegoapi:1.0
    ports: 
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./app.conf:/conf/app.conf:ro
    networks:
      - mynetwork
  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml
      - loki-data:/loki
    restart: unless-stopped
    networks:
      - mynetwork
  vector:
    image: timberio/vector:nightly-alpine
    command: ["--config", "/etc/vector/vector.yaml"]
    depends_on:
      - loki
      - firstbeegoapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - vector-data:/var/lib/vector
    restart: unless-stopped
    networks:
      - mynetwork
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - mynetwork
  grafana:
    image: grafana/grafana:nightly-slim
    user: "0"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - mynetwork
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - firstbeegoapi
    networks:
      - mynetwork
volumes:
  vector-data:
  loki-data:
networks:
  mynetwork:
    driver: bridge
